---
title: "Enrich the datasets with new columns."
output:
  rmdformats::readthedown:
        lightbox: true
        gallery: false
        df_print: paged
        toc_depth: 3
date: "`r Sys.Date()`"
editor_options: 
  chunk_output_type: console
params:
  data_dirpath: "/var/lib/R/project-evalR/run/package-evals-traced-corpus.4/"
  data_filepath: "/var/lib/R/project-evalR/run/package-evals-traced-corpus.4/calls.fst"
knit: (function(inputFile, encoding) {
  rmarkdown::render(inputFile, encoding = encoding, output_dir = "html") })
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      fig.align = "center",
                      fig.retina = 2,
                      fig.width = 10,
                      cache.lazy = FALSE)

library(tidyverse)
library(stringr)
library(viridis)
library(vctrs)
library(DT)
library(fst)
library(fs)

source("insights.R", local = knitr::knit_global())

source("inc/latextags.R")
create_tags(path("/var/lib/R/project-evalR/revalstudy/data", "analysisStable.tex"), prefix="", default=TRUE)
```


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Data

The analysis is being performed on a dataset read from file `r params$data_filepath`.

```{r file-info, echo=FALSE}
file_info(params$data_filepath)
```

```{r eval_in_base}
eval_base_functions <- c("autoload", "autoloader", "bquote", "by.default", "by.data.frame", "invokeRestartInteractively", "Ops.data.frame", "dget", 
                         "eval", "eval.parent", "evalq", "local", "with.default", "within.data.frame", "within.list", "replicate", "subset.data.frame",
                         "subset.matrix", "transform.data.frame", "match.arg", "char.expand", "max.col", "parseNamespaceFile", "source", "sys.source",
                         "stopfinot", "as.data.frane.table", "match.fun", "trace", "untrace", ".doTrace")
```


```{r load-data, echo=FALSE}
eval_calls_raw <-
    read_fst(params$data_filepath) %>%
    as_tibble()

eval_calls <- eval_calls_raw %>% filter(!caller_function %in% eval_base_functions)
```

There are so many calls that are similar:
```{r}
eval_calls_base <- eval_calls_raw %>% filter(caller_function %in% eval_base_functions) 
```

Let's remove the duplicate ones (but keep:

```{r}
eval_calls_base <- eval_calls_base %>% count(across(c(-eval_call_id, -starts_with("caller_stack"))), name = "nb_eval_calls") 
eval_calls <- eval_calls %>% count(across(c(-eval_call_id)), name = "nb_eval_calls")
```

```{r}
eval_calls_base <- eval_calls_base %>% 
    resolve_sexp_name(expr_expression_type) %>%
    resolve_sexp_name(expr_resolved_type) %>%
    resolve_sexp_name(enclos_type) %>%
    resolve_sexp_name(envir_type)

eval_calls <- eval_calls %>% 
    mutate(eval_call_package = extract_package_name(eval_call_srcref, file)) %>% 
    resolve_sexp_name(expr_expression_type) %>%
    resolve_sexp_name(expr_resolved_type) %>%
    resolve_sexp_name(enclos_type) %>%
    resolve_sexp_name(envir_type)
```



```{r}
eval_calls <- eval_calls %>% mutate(parse_args = if_else(is.na(expr_parsed_expression), NA, map_chr(expr_parsed_expression, extract_args_parse)))
```


```{r write_back}
write_fst(eval_calls, paste0(params$data_dirpath, "enriched_calls.fst"))

write_fst(eval_calls_base, paste0(params$data_dirpath, "base_calls.fst"))
```


