---
title: "Events"
output: html_document
params:
  base_dir: /home/aviral/projects/revalstudy2
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
for (x in c(
  "dplyr", 
  "DT",
  "fs",
  "fst",
  "ggplot2",
  "ggthemes",
  "lubridate",
  "readr",
  "purrr",
  "stringr",
  "tidyr",
  "tibble"
  )) {
  suppressPackageStartupMessages(library(x, character.only=TRUE))
}

knitr::opts_chunk$set(
  echo = TRUE,
  fig.align = "center",
  fig.retina = 2,
  fig.width = 10
)

# TODO: move into the package
source("inc/paths.R")
source("inc/setup.R")
source("inc/latextags.R")

options(repos="https://cran.r-project.org")
theme_set(theme_minimal())
create_tags(path(TAGS_DIR, "events.tex"), prefix="", default=TRUE)
```

```{r}
core_data <- read_fst(EVALS_SUM_CORE_FILE)
package_data <- read_fst(EVALS_SUM_PKGS_FILE)
kaggle_data <- read_fst(EVALS_SUM_KAGGLE_FILE)
program_data <- read_fst(PROGRAM_FILE)

all_data <- rbind(core_data, package_data, kaggle_data) %>% filter(eval_source != "testthat")
```

```{r preprocess-write-data}

eval_events_data <-
    all_data %>%
    filter(eval_function == "eval" | eval_function == "evalq") %>%
    select(eval_source_type, eval_source, direct_interpreter_eval, indirect_interpreter_eval, nb_ev_calls) %>%
    mutate(all_interpreter_eval = direct_interpreter_eval + indirect_interpreter_eval)
    
program_events_data <-
    program_data %>%
    select(direct_interpreter_eval, indirect_interpreter_eval)
```


```{r compute-side-effecting-write-counts}
all_events <- sum(program_events_data$direct_interpreter_eval + program_events_data$indirect_interpreter_eval)
eval_events <- sum(eval_events_data$direct_interpreter_eval * eval_events_data$nb_ev_calls)

r("All Event Count", all_events)
r("Eval Event Count", eval_events)

r("events max count", max(eval_events_data$all_interpreter_eval))

r("Eval Event All Perc", ratio(eval_events, all_events))
```

```{r compute-side-effecting-call-counts}
eval_events_data %>%
arrange(desc(all_interpreter_eval)) %>%
slice(1:500)

eval_events_by_source_type <-
    eval_events_data %>%
    group_by(eval_source_type, eval_source, all_interpreter_eval) %>%
    summarize(eval_count = sum(nb_ev_calls)) %>%
    ungroup()

datatable(eval_events_by_source_type)


eval_events_by_source_type %>%
arrange(desc(all_interpreter_eval)) %>%
datatable()

eval_events_by_source_type_summarized <-
    eval_events_by_source_type %>%
    mutate(all_interpreter_eval = if_else(all_interpreter_eval <= 9, as.character(all_interpreter_eval), "> 9")) %>%
    group_by(eval_source_type, all_interpreter_eval) %>%
    summarize(eval_count = sum(eval_count)) %>%
    ungroup()

datatable(eval_events_by_source_type_summarized)

eval_events_by_source_type_summarized_by_package <-
    eval_events_by_source_type %>%
    group_by(eval_source_type, eval_source) %>%
    summarize(total_interpreter_eval = sum(all_interpreter_eval * eval_count),
              max_interpreter_eval = max(all_interpreter_eval),
              average_interpreter_eval = total_interpreter_eval / sum(eval_count)) %>%
    ungroup()

datatable(eval_events_by_source_type_summarized_by_package)

p <- eval_events_by_source_type %>%
    ggplot(aes(x = eval_source_type, y = all_interpreter_eval, weight = eval_count)) +
    geom_boxplot() + 
    scale_y_log10()

p
```

```{r}
right <- c(100L, 10000L)
left <- right + 1L
right <- c(right, 2 * 10L^7L)
left <- c(0L, left)
package_counts <- integer(length(right))
core_counts <- integer(length(right))

incrementer <- function(eval_source_type, all_interpreter_eval, eval_count) {
    
    index <- 1
    while(all_interpreter_eval > right[index]) {
        index <- index + 1
    }
    if(eval_source_type == "core") {
        core_counts[index] <<- core_counts[index] + eval_count
    }
    else {
        package_counts[index] <<- package_counts[index] + eval_count
    }
}


ignore_result <-
    eval_events_by_source_type %>%
    group_by(eval_source_type, all_interpreter_eval) %>%
    summarize(eval_count = sum(eval_count)) %>%
    ungroup() %>%
    pmap(incrementer)
    

eval_events_table <-
    tibble(left = left, right = right, core_eval_count = core_counts, package_eval_count = package_counts) %>%
    mutate(core_eval_perc = round(100 * core_eval_count / sum(core_eval_count), 1),
           package_eval_perc = round(100 * package_eval_count / sum(package_eval_count), 1))


eval_events_table %>%
add_column(index = toupper(letters)[1:nrow(eval_events_table)]) %>%
pmap(function(left, right, core_eval_count, package_eval_count, core_eval_perc, package_eval_perc, index) {
    r(str_c("Events min range ", index), left)
    r(str_c("Events max range ", index), right)
    r(str_c("Events core eval count ", index), core_eval_count)
    r(str_c("Events core eval perc ", index), ratio(core_eval_perc, 100))
    r(str_c("Events package eval count ", index), package_eval_count)
    r(str_c("Events package eval perc ", index), ratio(package_eval_perc, 100))
    
})


datatable(eval_events_table)
```

mlogit, mboost, metafor, lavaan, foreach, gamlss, mclust, magrittr, VGAM

0-5
5-10
10-100
101-1000
1001-10000
10001-1000000





